//
//  declare.m
//  kriel
//
//  Created by Hyoun Woo Kim on 09. 06. 22.
//  Copyright 2009 __MyCompanyName__. All rights reserved.
//

#import "resourceManager.h"


@implementation ResourceManager

@synthesize resourceID;


-(id) init
{
	self = [super init];
	
	if(self)
	{		
		// the following values are used for 'tag' of AtlasSprites.
		NSArray *values = [NSArray arrayWithObjects: IDB_SWORD,
													 IDB_ARROW_LEFT1_2     ,       
													 IDB_ARROW_RIGHT1_2    ,
													 IDB_BLOCK_2           ,       
													 IDB_CROSS             ,       
													 IDB_FLOOR_2           ,       
													 IDB_GHOST1            ,       
													 IDB_GHOST2            ,       
													 IDB_KNIGHT1           ,       
													 IDB_KNIGHT2           ,       
													 IDB_HERO_DOWN1        ,       
													 IDB_HERO_DOWN2        ,       
													 IDB_HERO_LEFT1        ,       
													 IDB_HERO_LEFT2        ,       
													 IDB_ARROW_DOWN1_2     ,       
													 IDB_HERO_UP2          ,       
													 IDB_HERO_RIGHT2       ,       
													 IDB_HERO_UP1          ,       
													 IDB_HERO_RIGHT1       ,       
													 IDB_STICK             ,       
													 IDB_KING1             ,       
													 IDB_KING2             ,       
													 IDB_PRINCESS          ,       
													 IDB_SLIME1            ,       
													 IDB_SLIME2            ,       
													 IDB_KEY1              ,       
													 IDB_CUR_DOWN          ,       
													 IDB_CUR_LEFT          ,       
													 IDB_CUR_RIGHT         ,       
													 IDB_CUR_UP            ,       
													 IDB_PREV              ,       
													 IDB_NEXT              ,       
													 IDB_LOAD              ,       
													 IDB_SAVE              ,       
													 IDB_TITLE             ,       
													 IDB_HOWTOPLAY         ,       
													 IDB_GAMEOVER          ,       
													 IDB_ALLCLEAR          ,       
													 IDB_ICON_SWORD        ,       
													 IDB_ICON_GHOST        ,       
													 IDB_ICON_GUARD        ,       
													 IDB_ICON_KEY          ,       
													 IDB_ICON_SLIME        ,       
													 IDB_ICON_STICK        ,       
													 IDB_ICON_CROSS        ,       
													 IDB_VSBOX             ,       
													 IDB_ARROW_DOWN1_1     ,       
													 IDB_ARROW_DOWN2_1     ,       
													 IDB_ARROW_DOWN2_2     ,       
													 IDB_ARROW_DOWN3_1     ,       
													 IDB_ARROW_DOWN3_2     ,       
													 IDB_ARROW_DOWN4_1     ,       
													 IDB_ARROW_DOWN4_2     ,       
													 IDB_ARROW_LEFT1_1     ,       
													 IDB_ARROW_LEFT2_1     ,       
													 IDB_ARROW_LEFT2_2     ,       
													 IDB_ARROW_LEFT3_1     ,       
													 IDB_ARROW_UP2_1       ,       
													 IDB_ARROW_UP2_2       ,       
													 IDB_ARROW_UP3_1       ,       
													 IDB_ARROW_UP3_2       ,       
													 IDB_ARROW_UP4_1       ,       
													 IDB_ARROW_UP1_1       ,       
													 IDB_BKGND             ,       
													 IDB_ARROW_UP1_2       ,       
													 IDB_ARROW_UP4_2       ,       
													 IDB_ARROW_RIGHT1_1    ,       
													 IDB_ARROW_RIGHT2_1    ,       
													 IDB_ARROW_RIGHT2_2    ,       
													 IDB_ARROW_RIGHT3_1    ,       
													 IDB_ARROW_RIGHT3_2    ,       
													 IDB_ARROW_RIGHT4_2    ,       
													 IDB_ARROW_RIGHT4_1    ,
													 IDB_FLOOR_1           ,       
													 IDB_BLOCK_1           ,       
													 IDB_SLIME4            ,       
													 IDB_SLIME3            ,       
													 IDB_GHOST4            ,       
													 IDB_GHOST3            ,       
													 IDB_KNIGHT4           ,       
													 IDB_KNIGHT3           ,       
													 IDB_KEY4              ,       
													 IDB_KEY3              ,       
													 IDB_KEY2              ,       
													 IDB_EXIT_CLOSE        ,       
													 IDB_EXIT_OPEN4        ,       
													 IDB_EXIT_OPEN2        ,       
													 IDB_EXIT_OPEN3        ,       
													 IDB_EXIT_OPEN1        ,       
													 IDB_ARROW_LEFT4_2     ,       
													 IDB_ARROW_LEFT4_1     ,       
													 IDB_ARROW_LEFT3_2     ,       
													 IDB_LIFE              ,       
													 IDB_NUM9              ,       
													 IDB_NUM1              ,       
													 IDB_NUM2              ,       
													 IDB_NUM3              ,       
													 IDB_NUM4              ,       
													 IDB_NUM5              ,       
													 IDB_NUM6              ,       
													 IDB_NUM7              ,       
													 IDB_NUM8              ,       
													 IDB_NUM0              ,       
													 IDB_STAGE             ,       
													 IDB_CRUSH4            ,       
													 IDB_CRUSH2            ,       
													 IDB_CRUSH3            ,       
													 IDB_CRUSH1            ,       
													 IDB_QUIT              ,       
													 IDB_AGAIN             ,       
													 IDB_STAGECLEAR        ,       
													 IDB_EQUAL             ,       
													 IDB_DOT               ,       
													 IDB_PREVGRAY          ,       
													 IDB_NEXTGRAY          ,       
													 nil ];
		
		
		NSArray *keys = [NSArray arrayWithObjects:@"sword.png",
											   @"arrow_left1_2.png",
											   @"arrow_right1_2.png",
											   @"block_2.png",
											   @"cross.png",
											   @"floor_2.png",
											   @"ghost1.png",
											   @"ghost2.png",
											   @"guard1.png",
											   @"guard2.png",
											   @"hero_down1.png",
											   @"hero_down2.png",
											   @"hero_left1.png",
											   @"hero_left2.png",
											   @"arrow_down1_2.png",
											   @"hero_up2.png",
											   @"hero_right2.png",
											   @"hero_up1.png",
											   @"hero_right1.png",
											   @"stick.png",
											   @"king1.png",
											   @"king2.png",
											   @"princess.png",
											   @"slime1.png",
											   @"slime2.png",
											   @"key1.png",
											   @"cur_down.png",
											   @"cur_left.png",
											   @"cur_right.png",
											   @"cur_up.png",
											   @"prev.png",
											   @"next.png",
											   @"Load.png",
											   @"Save.png",
											   @"Title.png",
											   @"HowToPlay.png",
											   @"gameover.png",
											   @"AllClear.png",
											   @"icon_sword.png",
											   @"icon_ghost.png",
											   @"icon_guard.png",
											   @"icon_key.png",
											   @"icon_slime.png",
											   @"icon_stick.png",
											   @"icon_cross.png",
											   @"vsbox.png",
											   @"arrow_down1_1.png",
											   @"arrow_down2_1.png",
											   @"arrow_down2_2.png",
											   @"arrow_down3_1.png",
											   @"arrow_down3_2.png",
											   @"arrow_down4_1.png",
											   @"arrow_down4_2.png",
											   @"arrow_left1_1.png",
											   @"arrow_left2_1.png",
											   @"arrow_left2_2.png",
											   @"arrow_left3_1.png",
											   @"arrow_up2_1.png",
											   @"arrow_up2_2.png",
											   @"arrow_up3_1.png",
											   @"arrow_up3_2.png",
											   @"arrow_up4_1.png",
											   @"arrow_up1_1.png",
											   @"back.png",
											   @"arrow_up1_2.png",
											   @"arrow_up4_2.png",
											   @"arrow_right1_1.png",
											   @"arrow_right2_1.png",
											   @"arrow_right2_2.png",
											   @"arrow_right3_1.png",
											   @"arrow_right3_2.png",
											   @"arrow_right4_2.png",
											   @"arrow_right4_1.png",
											   @"floor_1.png",
											   @"block_1.png",
											   @"slime4.png",
											   @"slime3.png",
											   @"ghost4.png",
											   @"ghost3.png",
											   @"guard4.png",
											   @"guard3.png",
											   @"key4.png",
											   @"key3.png",
											   @"key2.png",
											   @"door_close.png",
											   @"door_open4.png",
											   @"door_open2.png",
											   @"door_open3.png",
											   @"door_open1.png",
											   @"arrow_left4_2.png",
											   @"arrow_left4_1.png",
											   @"arrow_left3_2.png",
											   @"life.png",
											   @"num9.png",
											   @"num1.png",
											   @"num2.png",
											   @"num3.png",
											   @"num4.png",
											   @"num5.png",
											   @"num6.png",
											   @"num7.png",
											   @"num8.png",
											   @"num0.png",
											   @"stage.png",
											   @"crush4.png",
											   @"crush2.png",
											   @"crush3.png",
											   @"crush1.png",
											   @"Quit.png",
											   @"Again.png",
											   @"StageClear.png",
											   @"equal.png",
											   @"dot.png",
											   @"prev_d.png",
											   @"next_d.png", 
											   nil];
	    
		// Create dictionary for resouce id.
		resourceID = [NSDictionary dictionaryWithObjects:values forKeys:keys];
	}
		
	return self;
}

@end