//
//  declare.h
//  kriel
//
//  Created by Hyoun Woo Kim on 09. 06. 22.
//  Copyright 2009 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>

// All these define values are used for 'tag' for AtlasSprite 

	
#define IDB_SWORD                       @"99"
#define IDB_ARROW_LEFT                  @"100"
#define IDB_ARROW_LEFT1_2               @"101"
#define IDB_ARROW_RIGHT                 @"102"
#define IDB_ARROW_RIGHT1_2              @"103"
#define IDB_ARROW_UP                    @"104"
#define IDB_BLOCK                       @"105"
#define IDB_BLOCK_2                     @"106"
#define IDB_CROSS                       @"107"
#define IDB_DOOR_CLOSE                  @"108"
#define IDB_EXIT_CLOSE                  @"109"
#define IDB_DOOR_OPEN                   @"110"
#define IDB_EXIT_OPEN                   @"111"
#define IDB_FLOOR                       @"112"
#define IDB_FLOOR_2                     @"113"
#define IDB_GHOST1                      @"114"
#define IDB_GHOST2                      @"115"
#define IDB_GUARD1                      @"116"
#define IDB_KNIGHT1                     @"117"
#define IDB_GUARD2                      @"118"
#define IDB_KNIGHT2                     @"119"
#define IDB_HERO_DOWN1                  @"120"
#define IDB_HERO_DOWN2                  @"121"
#define IDB_HERO_LEFT1                  @"122"
#define IDB_HERO_LEFT2                  @"123"
#define IDB_ARROW_DOWN                  @"124"
#define IDB_ARROW_DOWN1_2               @"124"
#define IDB_HERO_UP2                    @"125"
#define IDB_HERO_RIGHT2                 @"126"
#define IDB_HERO_UP1                    @"127"
#define IDB_HERO_RIGHT1                 @"128"
#define IDB_STICK                       @"129"
#define IDB_KING1                       @"130"
#define IDB_KING2                       @"131"
#define IDB_PRINCESS                    @"132"
#define IDB_SLIME1                      @"133"
#define IDB_SLIME2                      @"134"
#define IDB_KEY                         @"135"
#define IDB_KEY1                        @"135"
#define IDB_BACK                        @"136"
#define IDB_BKGND                       @"136"
#define IDB_VSBOX                       @"139"
#define IDB_CUR_DOWN                    @"140"
#define IDB_CUR_LEFT                    @"141"
#define IDB_CUR_RIGHT                   @"142"
#define IDB_CUR_UP                      @"143"
#define IDB_PREV                        @"145"
#define IDB_NEXT                        @"146"
#define IDB_LOAD                        @"147"
#define IDB_SAVE                        @"148"
#define IDB_TITLE                       @"149"
#define IDB_HOWTOPLAY                   @"150"
#define IDB_GAMEOVER                    @"151"
#define IDB_ALLCLEAR                    @"152"
#define IDB_ICON_SWORD                  @"153"
#define IDB_ICON_GHOST                  @"154"
#define IDB_ICON_GUARD                  @"155"
#define IDB_ICON_KEY                    @"156"
#define IDB_ICON_SLIME                  @"157"
#define IDB_ICON_STICK                  @"158"
#define IDB_ICON_CROSS                  @"159"
#define IDB_ARROW_DOWN1_1               @"161"
#define IDB_ARROW_DOWN2_1               @"164"
#define IDB_ARROW_DOWN2_2               @"165"
#define IDB_ARROW_DOWN3_1               @"166"
#define IDB_ARROW_DOWN3_2               @"167"
#define IDB_ARROW_DOWN4_1               @"168"
#define IDB_ARROW_DOWN4_2               @"169"
#define IDB_ARROW_LEFT1_1               @"170"
#define IDB_ARROW_LEFT2_1               @"172"
#define IDB_ARROW_LEFT2_2               @"173"
#define IDB_ARROW_LEFT3_1               @"174"
#define IDB_ARROW_UP2_1                 @"177"
#define IDB_ARROW_UP2_2                 @"178"
#define IDB_ARROW_UP3_1                 @"179"
#define IDB_ARROW_UP3_2                 @"180"
#define IDB_ARROW_UP4_1                 @"181"
#define IDB_ARROW_UP1_1                 @"182"
#define IDB_ARROW_UP1_2                 @"183"
#define IDB_ARROW_UP4_2                 @"184"
#define IDB_ARROW_RIGHT1_1              @"185"
#define IDB_ARROW_RIGHT2_1              @"186"
#define IDB_ARROW_RIGHT2_2              @"187"
#define IDB_ARROW_RIGHT3_1              @"188"
#define IDB_ARROW_RIGHT3_2              @"189"
#define IDB_ARROW_RIGHT4_2              @"190"
#define IDB_ARROW_RIGHT4_1              @"191"
#define IDB_FLOOR_1                     @"192"
#define IDB_BLOCK_1                     @"193"
#define IDB_SLIME4                      @"194"
#define IDB_SLIME3                      @"195"
#define IDB_GHOST4                      @"196"
#define IDB_GHOST3                      @"198"
#define IDB_KNIGHT4                     @"200"
#define IDB_KNIGHT3                     @"201"
#define IDB_KEY4                        @"202"
#define IDB_KEY3                        @"203"
#define IDB_KEY2                        @"204"
#define IDB_EXIT_OPEN4                  @"209"
#define IDB_EXIT_OPEN2                  @"210"
#define IDB_EXIT_OPEN3                  @"211"
#define IDB_EXIT_OPEN1                  @"212"
#define IDB_ARROW_LEFT4_2               @"213"
#define IDB_ARROW_LEFT4_1               @"214"
#define IDB_ARROW_LEFT3_2               @"215"
#define IDB_LIFE                        @"216"
#define IDB_NUM9                        @"217"
#define IDB_NUM1                        @"218"
#define IDB_NUM2                        @"219"
#define IDB_NUM3                        @"220"
#define IDB_NUM4                        @"221"
#define IDB_NUM5                        @"222"
#define IDB_NUM6                        @"223"
#define IDB_NUM7                        @"224"
#define IDB_NUM8                        @"225"
#define IDB_NUM0                        @"226"
#define IDB_SCORE                       @"227"
#define IDB_STAGE                       @"228"
#define IDB_CRUSH4                      @"229"
#define IDB_CRUSH2                      @"230"
#define IDB_CRUSH3                      @"231"
#define IDB_CRUSH1                      @"232"
#define IDB_QUIT                        @"233"
#define IDB_AGAIN                       @"234"
#define IDB_STAGECLEAR                  @"235"
#define IDB_EQUAL                       @"236"
#define IDB_DOT                         @"237"
#define IDB_PREVGRAY                    @"238"
#define IDB_NEXTGRAY                    @"239"

@interface ResourceManager : NSObject
{
	NSDictionary *resourceID;
}

@property (copy, readwrite) NSDictionary *resourceID;

@end
